<div class="login-wrap">
    <div class="panel panel-default">
        <div class="panel-heading panel-primary">
            <i class="icon-login"></i> Login
        </div>
        <div class="panel-body">
            <form method="post" action="<?php echo $this->url('auth', array('action' => 'login')); ?>">
                <?php if ($this->code) { ?>
                    <div class="form-group">
                        <div class="alert alert-danger text-center">
                            <strong>Authentication Failed.</strong> Invalid username/password combination.
                        </div>
                    </div>
                <?php } ?>
                <div class="form-group">
                    <label for="username">Enter username</label>
                    <input type="text" name="username" id="username" class="form-control" placeholder="Enter username">
                </div>
                <div class="form-group">
                    <label for="password">Enter password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Enter password">
                </div>

                <hr/>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>
    </div>
</div>