<ul class="<?php echo $this->navigation($this->container)->menu()->getUlClass(); ?>" id="main-navigation">
    <?php
    foreach ($this->container as $page) {
        if ($this->navigation()->accept($page)) {
            $active = ($page->isActive(true) ? ' class="active-menu"' : '');
            $target = ($page->getTarget() != '' ? 'target="' . $page->getTarget() . '"' : '');
            $icon = ($page->get("icon") !== '' ? '<i class="' . $page->get('icon') . '"></i>' : '');
            $label = $this->escapeHtml(
                    $this->translate($page->getLabel(), $this->navigation($this->container)->getTranslatorTextDomain())
            );
            ?>
            <li>
                <a href="<?php echo ($page->hasPages() ? '#' : $page->getHref()); ?>" <?php echo $active, ' ', $target; ?> >
                    <?php echo $icon, $label, ($page->hasPages() ? '<span class="icon-down-dir"></span>' : ''); ?>
                </a>
                <?php
                if ($page->hasPages()) {
                    //check if access is allowed at least one item
                    $access = false;
                    foreach ($page->getPages() as $child) {
                        if ($this->navigation()->accept($child) && $child->get('separator') !== true) {
                            $access = true;
                            break;
                        }
                    }
                    if ($access) {
                        ?>
                        <ul class="nav nav-second-level <?php echo ($active ? 'collapse in' : ''); ?>">
                            <?php foreach ($page->getPages() as $child) { ?>
                                <li>
                                    <a href="<?php echo $child->getHref(); ?>" <?php echo ($child->isActive() ? 'class="active-submenu"' : ''); ?>><?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($this->container)->getTranslatorTextDomain())); ?></a>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
                    <?php
                }
            }
        }
    }
    ?>
</ul>
<a href="#" class="navbar-hide"><i class="icon-left-dir"></i> Hide</a>